---
- name: Setup
  block:
    - include_tasks: build.yml

    - include_tasks: init.yml

    - include_tasks: genesis.yml

    - include_tasks: cosmovisor/setup.yml

    - include_tasks: cosmovisor/upgrades.yml
      when: (upgrade is defined) and (upgrade != "")

    - include_tasks: snapshot.yml
      when: apply_snapshot == "yes"

    - include_tasks: config.yml

    - name: Restart cosmovisor
      command: echo "restarting cosmovisor"
      notify: "restart cosmovisor"
  when: (binary_upgrade is not defined) or (binary_upgrade == "false") or (binary_upgrade == "")

- name: Upgrade
  block:
    - include_tasks: build.yml

    - include_tasks: cosmovisor/upgrades.yml

    - name: Restart cosmovisor
      command: echo "restarting cosmovisor"
      notify: "restart cosmovisor"
      when: (restart_cosmovisor is defined) and (restart_cosmovisor == "true")
  when: (binary_upgrade is defined) and (binary_upgrade == "true")
